### ISSUE TITLE
Canvas arrow labels visibility issue

### ISSUE THREAD

**Issue by imrehg** [7368697661/Origami#17]
When adding canvas items, connecting them with arrows, and adding a label on top of the arrow, the arrow doesn't have a gap and/or z-ordering is off and/or something else that makes it less readable.

Screenshot with Origami enabled:

<img width="629" alt="Screenshot 2023-02-15 at 12 59 36" src="https://user-images.githubusercontent.com/38863/218936454-3bbb36cf-e1fb-41b9-8f30-9c82fb7e16a6.png">

Screenshot with default theme:

<img width="588" alt="Screenshot 2023-02-15 at 12 59 22" src="https://user-images.githubusercontent.com/38863/218936441-413a1817-11fd-4f45-9d02-08366942a378.png">

Otherwise the canvas looks pretty neat in multiple ways, so cheers for the tweaks!

**Comment by 7368697661** [comment]
sorry i never commented, that is an unfortunate side effect for a workaround to get arrow heads rendering over the card backgrounds. i had to pull this design for now, because i can't get it up to a level of stability i feel comfortable sharing :) hope to have a new version at some point when i can fully review canvas features (for now this also fixes #16, with special features as an opt in :))
